### ISSUE TITLE
[JFG-833] Constant Rate Timer

### ISSUE THREAD

**Issue by IvanMamontov** [griddynamics/jagger#577]
As a Jagger user I would like to have an ability to have constant-rate timer(CRT).
This timer introduces variable pauses, calculated to keep the total throughput (in terms of samples per second) as close as possible to a give figure. Of course the throughput will be lower if the server is not capable of handling it, or if other timers or time-consuming test elements prevent it.
There are two possible input parameters:
- Target Throughput - throughput we want the timer to try to generate.
- Throughput Calculation Strategy:
  - per thread - each thread will try to maintain the target throughput. The overall throughput will be proportional to the number of active threads.
  - per all threads - the target throughput is divided amongst all the active threads in the group. Each thread will delay as needed, based on when it last ran.

**Comment by dlatnikov** [comment]
done in 1.2.6 (RPS load configuration)
