### ISSUE TITLE
Do you have any plans to Jagger evolution?

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [griddynamics/jagger#593]
Hi team,

I have done several enhancements for Jagger like migration to Java 8 and support for distributed deployment without usage of Jenkins and shell scripts. And before to spent time to prepare pull requests I want to know if the project is alive, because I do not see any active development in your repository. Is Jagger dead? If not, then it will be nice to discuss future plans for Jagger evolution in any bar/cafe in Saint-Petersburg.

**Comment by dlatnikov** [comment]
Hi Vladimir

We are continuing using Jagger in our existing and new projects, however there is no development going on. It would be great to discuss your ideas

Dmitry

**Comment by vladimir-bukhtoyarov** [comment]
Hi Dmitry,

What you think about to meet on the next week? I suppose that [Postscriptum](https://yandex.ru/maps/2/saint-petersburg/?z=14&ll=30.311107%2C59.965241&l=map&origin=jsapi_2_1_38&from=api-maps&um=constructor%3AT_qToJHhWUkV1TnG14omGvK2pfeqr7g6) would be a good place for meeting.
