### ISSUE TITLE
Query lost part of its parameter if this parameter contains symbol &.

### ISSUE THREAD

**Issue by Lhfvgbh** [griddynamics/jagger#859]
Example: search result for
“_Bikini & Swim Bottom_”
 turns into result for phrase
“_Bikini_ ”
and is not the one that was expected.

According to World Wide Web Consortium, there are reserved symbols that can be used in URL and have their own purpose. To define the interpretation of URL, all symbols that have been reserved must be converted. Symbol **&** should be converted to **%26** in URL query if it was passed inside query message.

I would like to pass search phrase as a query parameter. Current Jagger URL parser cannot recognize sign & inside query parameter and cannot turn it into %26 as required. Instead of Bikini%20%26%20Swim%20Bottom, it return Bikini%20&%20Swim%20Bottom.
That means that my search phrase “Bikini & Swim Bottom” turns into “Bikini ” and return wrong query result.
There could be an another problem if I would have some boolean parameter "_clear_”: “_clean&clear_" query search phrase could turn from _clean%26clear_ into _clean&clear_  with "_clean_" search result and action to clear some data.

This issue makes it not possible to process query message if it contains sign **&**. Please consider implementing of correct URL parser in order to correspond  World Wide Web Consortium.

**Comment by ctpe71ok** [comment]
fixed in 2.0.1-m3
